# Set the build language to Python
language: python

# Set the python version to 3.8
python: 
  - "3.7"
  - "3.8"

# Install the codecov pip dependency
install:
  - pip install .
  - pip install nose parameterized

# Run the unit test
script:
  - nosetests --with-coverage --cover-package=banditzoo

# Push the results back to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
