# Set the build language to Python
language: python

# Set the python version to 3.8
python: 3.8

# Install the codecov pip dependency
install:
  - pip install .
  - pip install nose coverage parameterized
  - pip install coveralls codecov

# Run the unit test
script:
  - python setup.py nosetests --with-coverage --cover-package pypiview

# Push the results back to codecov
after_success:
  - codecov coveralls